school_notebooks:
  repo_id: "ai-forever/school_notebooks_EN"

  files:
    train_annotations: "annotations_train.json"
    val_annotations: "annotations_val.json"
    test_annotations: "annotations_test.json"
    images_zip: "images.zip"

  output_dir: "data/01_raw"

data_preparation:
  images_base_dir: "data/01_raw/images.zip"
  n_pages: 100
  model_dir: "microsoft/trocr-base-handwritten"
  cer_threshold: 0.25

model_training:
  pretrained_model_name: "microsoft/trocr-base-handwritten"
  max_target_length: 256
  output_dir: "data/06_models/trocr-line"

  training_args:
    output_dir: "data/06_models/trocr-line-hf"
    overwrite_output_dir: true
    
    do_train: true
    do_eval: true
    predict_with_generate: true

    per_device_train_batch_size: 4
    per_device_eval_batch_size: 4
    num_train_epochs: 20
    learning_rate: 1e-5
    warmup_ratio: 0.1 

    save_strategy: "epoch"
    eval_strategy: "epoch"
    logging_strategy: "steps"
    logging_steps: 50
    
    fp16: false
    optim: "adamw_torch"
    weight_decay: 0.01

    load_best_model_at_end: true
    metric_for_best_model: "eval_cer"
    greater_is_better: false
    save_total_limit: 2
    report_to: "none"